### ISSUE TITLE
Enrich Readme 

### ISSUE THREAD

**Issue by maybeec** [oasp-forge/oasp4js-rev#17]
- [x] with information on what this application is about
- [x] which technologies are in use
- [x] how to start run it locally (step by step)
- [x] how to run tests

you may also link to the wiki if there is anything documented which might be duplicated.

**Comment by cbeldacap** [comment]
### What this app is about?

The sample-app is a management of a restaurant. Users will log in in the app, so they can perform some actions on it (always depending on their profile). 

3 different views are able to be used/navigated:
- Tables: It will be a CRUD that will contain data about the tables in the restaurant, as well as their own attributes such as the state of each one of them (FREE/RESERVED/OCCUPIED).
- Details/Edit: This view will be displayed from "Tables", clicking on "Edit" button when a table's already selected. It will contain another CRUD of commands asked on that Table. So it will be possible to add some more, remove, and so on.
- Kitchen: Every action that is performed on Details view will have its reflect on that view. It will be possible to perform some actions over those commands as well, such as "cancel" (when they are ready).

There will be 3 kind of users:
- Chief (username:"chief"/password:"chief") : Access to both Tables and Kitchen views.
- Cook ("cook"/"cook") : Access only to Kitchen view
- Waiter ("waiter/waiter") : Access only to Tables view

### Which technologies are in use
TODO

### How to start run it locally
TODO

### How to run tests
TODO

**Comment by cbeldacap** [comment]
### Which technologies are in use?

As we are developing this sample-app in Angular2, we are forced to use an environment on which TypeScript can be supported, so we use Atom. It allows us to install packages from the environment itself. TypeScript is being the main language, but also HTML with angular2 elements (I will try to explain it later on this Issue).

**Comment by maybeec** [comment]
just add it to the [README.md](https://github.com/oasp-forge/oasp4js-rev/blob/development/README.md)

**Comment by cbeldacap** [comment]
### How to start run it locally? (step by step)

1. install Atom and Node.js (we use "npm" for running, testing and installing).
2. clone oasp4js-rev repo to your local
