### ISSUE TITLE
First integration with oasp4j-sample

### ISSUE THREAD

**Issue by maybeec** [oasp-forge/oasp4js-rev#4]
Based on #3 we should 
- [ ] integrate the security module to the sample app and 
- [ ] integrate it with the oasp4j sample app to assure compatibility

**Comment by RobertoGM** [comment]
At the moment, full focused on this issue and #3 with @cbeldacap

**Comment by RobertoGM** [comment]
integrated with oasp-sample, only security module is left, which has his own issue #3
