### ISSUE TITLE
Create an angular webcomponent 'paginated table'

### ISSUE THREAD

**Issue by maybeec** [oasp-forge/oasp4js-rev#5]
As a first step, we should start implementing an angular component for a paginated table in a new ui module to be created. It should be possible to 
- [ ] sort by columns (server-side)
- [x] filter by column values (server-side)
- [x] paginate (server-side)

For information about the server API have a look at the [oasp4j documentation](https://github.com/oasp/oasp4j/wiki/guide-service-layer#parameterized-loading-of-a-resource) or the [oasp4j-sample application's code](https://github.com/oasp/oasp4j/tree/develop/samples/core/src/main/java/io/oasp/gastronomy/restaurant) directly.

**Comment by RobertoGM** [comment]
At the moment there is a table in restaurant app with a panel to filter columns, a pagination component and a icon for each column to sort the values (ascending or descending). The only component completely independent is the pagination. Should I put all of this together in a component when you pass as inputs the information to build a "table" component (such as array of column names, data...) or leave each component (filter, table and pagination) separated?

**Comment by RobertoGM** [comment]
Table component done, with an auxiliar independent pagination component, both still do all his logic in front-end, i will change this as soon as i can.

**Comment by RobertoGM** [comment]
Search component implemented with two default buttons: clear and search.

orderBy only orders current page rows because the data that table-grid component manages is only the X number of rows displaying in that page, this should be fixed once we start using server back-end

**Comment by maybeec** [comment]
Please also have a lookt at ag-grid to not reimplement everything by hand. See also the discussion of oasp/oasp4js#45
