### ISSUE TITLE
Migrate oasp4js-i18n

### ISSUE THREAD

**Issue by maybeec** [oasp-forge/oasp4js-rev#6]
As one of the first steps, we should migrate the oasp4js-i18n module to assure compliant UI implementation from the first day on.
See https://github.com/oasp/oasp4js/tree/development/app/oasp/oasp-i18n
- [ ] implement oasp4js-i18n module
- [ ] document the configuration and usage in the [wiki](https://github.com/oasp/oasp4js-rev/wiki/guide-i18n)

**Comment by RobertoGM** [comment]
i18n working and documented in the wiki
