### ISSUE TITLE
Create tablemanagement search-table dialog

### ISSUE THREAD

**Issue by maybeec** [oasp-forge/oasp4js-rev#7]
- [ ] Reimplement the [tablemanagement's search-table dialog](http://oasp-ci.cloudapp.net/oasp4j-sample/jsclient/#/table-mgmt/table-search) in the new oasp4js-sample application.
- [ ] explicitly document any introduced naming conventions on classes/files/folders in the [wiki](https://github.com/oasp/oasp4js-rev/wiki/oasp-code-contributions)

**Comment by maybeec** [comment]
- will depend on #5 
- might depend on #6 for already correct implementation with i18n
- server integration might depend on #4

**Comment by RobertoGM** [comment]
Search component implemented
